### ISSUE TITLE
Kapselung: Liste mit allen verlinkten Modellen bei Source-Knoten

### ISSUE THREAD

**Issue by fischJan** [qualicen/specmate#188]
**User Story**
Als ein Nutzer möchte ich sehen, welche Knoten mit einem verlinkten Knoten in Verbindung stehen, damit ich weiß, welche Auswirkungen meine Änderungen an dem Knoten haben.

**Acceptance Criteria**
- An Knoten, die referenziert werden, wird eine Liste aller Modelle angezeigt (Name des Modells inkl. Link), in denen der Knoten referenziert wird.

- An Knoten, die einen anderen Knoten referenzieren, wird das Modell angezeigt (Name des Modells inkl. Link), in dem sich der referenzierte Knoten befindet.

- Die oben genannten Referenzinformationen werden auf der rechten Seite im Eigenschaftsbereich angezeigt.

**Comment by sebeder** [comment]
Hi @fischJan ,

ich habe da noch Fragen:

- zu "An Knoten, die referenziert werden, wird eine Liste aller referenzierenden Knoten angezeigt.": Welche Informationen zu den referenzierenden Knoten soll angezeigt werden? Denn Name/Variable/Condition sind hier nicht so zweckdienlich, weil die ja ohnehin den Daten aus dem referenzierten Knoten entsprechen. Ich würde hier eher die Modelle anzeigen, in denen ein Knoten referenziert wird (mit link dahin). OK?
- zu "An Knoten, die einen anderen Knoten referenzieren, wird der Knoten angezeigt, der referenziert wird.": Soll hier auch eher das Modell angezeigt werden, in welchem der referenzierte Knoten ist? Denn Variable und Condition werden ohnehin im Graphen angezeigt. Auch hier würde ich einen Link zum entsprechenden Modell einbauen. OK?

**Comment by fischJan** [comment]
Hi @sebeder ,

du hast vollkommen Recht. Wir sollten die Modelle anzeigen, in denen die Knoten referenziert werden. Ich passe die Akzeptanzkriterien an.
