### ISSUE TITLE
Kapselung: Verlinkung von Knoten bestehender CEGs (Fall 1: 1 - 1 Mapping, da die verlinkte Variable nur durch einen Effekt dargestellt wird)

### ISSUE THREAD

**Issue by fischJan** [qualicen/specmate#189]
**User Story**
Als Nutzer möchte ich große Modelle als einzelne Knoten in anderen wiederverwenden, um nicht immer wieder die gleichen Inhalte modellieren zu müssen, sondern auf bereits existierende Arbeit zurückgreifen zu können.

**Acceptance Criteria**
1. Wenn der Nutzer per Rechtsklick auf einen Eingangsknoten klickt (Ein Ausangsknoten sind all diejenigen Knoten ohne (!) eine eingehende Verbindung), wird auf der rechten Seite in der Informationsleiste ein Button angezeigt "Link Exisiting Model".
2. Wenn der Nutzer auf diesen Button drückt, wird er aufgefordert den Namen des Modells einzugeben, welches er mit dem Knoten verlinken möchte.
3. Specmate sucht in der Liste der bestehenden Modelle und zeigt dieses bei erfolgreichem Finden an.
4. Sollte kein Modell mit dem eingegebenen Namen übereinstimmen, zeigt Specmate eine Fehlermeldung an mit dem Kommentar "Model cannot be found".
5. Klickt der Nutzer auf den Namen eines Modells in der oben beschriebenen Liste, zeigt Specmate alle Effekte dieses Modells an. 
6. Der Nutzer darf nur eines dieser Effekte auswählen und es mit dem Knoten im neuen Modell verlinken.
7. Klickt der Nutzer auf den Namen des Effekts, werden die Informationen aus diesem Effekt in den zu verlinkenden Knoten übernommen (z.B. Effekt ist = "HKV" "is present"; dann werden sowohl der Variablen Name als auch die Condition in den neuen Knoten übernommen).

**Comment by fischJan** [comment]
@sebeder welcher Pull Request bezieht sich auf das Issue?

**Comment by sebeder** [comment]
Hier gibt es keinen PR, wenn ich das richtig sehe.

**Comment by sebeder** [comment]
Und ich stelle mir gerade die Frage, ob wir das so, wie es ist implementieren, oder ob das durch die Knoten-Verlinkung bereits abgeschlossen ist. Ich hab hier den Faden verloren.
