### ISSUE TITLE
Kapselung: Warnung beim Verändern von Knoten im verlinkten Modell

### ISSUE THREAD

**Issue by sebeder** [qualicen/specmate#190]
**User Story**

Als Nutzer möchte ich wissen, wenn sich ein verlinktes Modell verändert hat, damit ich immer einen Überblick über aktuelle Änderungen habe.

**Acceptance Criteria**

1. Wenn der Nutzer einen Knoten im verlinkten Modell markiert wird eine Warnmeldung angezeigt.
2. Bricht der Nutzer die Aktion in der Warnmeldung ab, werden alle markierten Knoten deselektiert und etwaige Veränderungen an den selektierten Knoten (z.B. Verschiebung) rückgängig gemacht.
3. Fährt der Nutzer mit der Aktion fort, können an dem betreffenden verlinkten Knoten Änderungen durchgeführt werden, ohne, dass der Benutzer die Warnmeldung für diesen Knoten noch einmal angezeigt bekommt, solange das Modell geöffnet ist.
4. Navigiert der Nutzer vom betreffenden Modell weg, und öffnet das Modell erneut, werden wieder für alle verlinkten Knoten die Warnmeldungen angezeigt.

**Comment by sebeder** [comment]
Hi @fischJan , Ich hab da immer noch meine Probleme mit dem Issue. Nun aber eher auf Implementierungsseite. Das Problem ist, dass ein Benutzer prinzipiell seine Änderungen immer sofort auf dem Datenbestand im Client durchführt. Eine Meldung, nachdem die Änderung stattgefunden hat, müsste dann ein "Rückgängig" triggern. Das ist aus zwei Gründen komisch:

- Der Nutzer hat die Änderung schon durchgeführt und das ist ja komisch, ihn erst nachher zu warnen
- Das weit größere Problem ist, dass falls der Nutzer die Änderung nicht autorisiert, ja ein Rückgängig erfolgen muss, was aber wieder eine Änderung am betreffenden Knoten ist, welche dann ja wieder autorisiert werden muss. Blöd ist, dass so wie Specmate funktioniert, können wir nicht mitgeben, welche Änderung jetzt dann gleich ein Rückgängig sein wird, welches implizit schon autorisiert wurde.

Daher habe ich folgenden Vorschlag: Sobald ein Nutzer einen verlinkten Knoten zum Editieren auswählt, kann er ihn zum Editieren freischalten. Also der ist erst disabled, aber wenn er dann freigeschaltet ist, kann er editiert werden. Wäre das eine Lösung? Die Freischaltung ist dann so lange aktiv, wie der Benutzer das aktuelle Modell geöffnet hat und wird danach verworfen. Wäre das OK?

**Comment by fischJan** [comment]
@sebeder finde den Vorschlag gut ! Optimal wäre, wenn man per Rechtsklick nicht nur "Delete" auswählen könnte, sondern man auch dieses "Freischalten" per Rechtsklick machen könnte.

**Comment by fischJan** [comment]
Bei Klick auf verlinkten Knoten kommt ein Warnfenster "Achtung Sie editieren einen verlinkten Knoten". Kein Freischalten per Rechtsklick.
