### ISSUE TITLE
Knotenverlinkung funktioniert nicht mit Modellen in der Bibliothek

### ISSUE THREAD

**Issue by junkerm** [qualicen/specmate#203]
**Describe the bug**
Knotenverlinkung funktioniert nicht, wenn ein Link zu einem Knoten gemacht werden soll, der sich in einem Modell in der Bibliothek befindet.

**To Reproduce**
1. Create a model in the library
2. Create a sedond model (in the library or somewhere else)
3. In the second model create a linked node
4. In the modal window search for the first model 
5. The model is not found

**Expected behavior**
The model is found and i can select a node to link to

**Comment by sebeder** [comment]
Hi @junkerm , I just tried to reproduce the error, but I could not. Can we later check that together?

**Comment by sebeder** [comment]
@junkerm , the best branch would be link-models-base

**Comment by sebeder** [comment]
@junkerm , we discussed that and this works, but not with models with a name that ends with a number. I think we can close this, right?
