### ISSUE TITLE
Undo delete linked node opens linking popup

### ISSUE THREAD

**Issue by junkerm** [qualicen/specmate#207]
**Describe the bug**
When undo-ing a deletion of a linked node, the node is not recreated, but instead the linking popup is shown.

**To Reproduce**
1. Create a linked node
2. Delete the linked node
3. Hit undo

**Expected behavior**
The deleted linked node is recreated without showing a popup

**Comment by fischJan** [comment]
@sebeder In den von mir falsch archivierten Trello Karten war noch folgende Frage von dir drin: **Löschen von verlinkten Knoten: Soll das möglich sein, oder soll der Nutzer schon daran gehindert werden?** Ich würde mir folgende Funktion wünschen:

Fall 1: Ich befinde mich in einem CEG, in welchem ein Knoten mit einem anderen Knoten (der Ausgangsknoten) aus einem anderen CEG verlinkt ist

- Einen solchen Knoten kann ich ohne Probleme löschen. Da kommt kein spezielles Warnfenster oder ähnliches. Wir behandeln diesen Fall also wie das "normale" Löschen eines Knoten.

Fall 2: Ich lösche den Ausgangsknoten (Das würde bedeuten, dass alle CEGs mit Knoten, die auf diesen Ausgangsknoten referenzieren, ungültige Links haben)

- Hier muss auf jeden Fall ein Warnfenster kommen: "If you delete this node, other CEG models will become invalid". Wenn man dann immer noch auf OK drückt, dann müssen wir den Ausgangsknoten und alle Knoten, die diesen referenzieren, auch löschen. Die CEGs werden dann als fehlerhaft im Projekt Explorer angezeigt.

Siehst du das ähnlich oder eher anders? :)
