### ISSUE TITLE
Automatischer Zeilenumbruch und Größenanpassung von Knoten

### ISSUE THREAD

**Issue by fischJan** [qualicen/specmate#224]
Um Modelle in Specmate einfacher und übersichtlicher entwerfen zu können, wären folgende Verbesserungen wünschenswert:

1. Bei der Benennung der Knoten gibt es einen automatischen Zeilenumbruch, so dass der Text innerhalb des Knotens bleibt.

2. Die Knotengröße passt sich entsprechend der Textlänge automatisch an

**EDIT(wehrlean): Punkt 3 in eigenes Issue ausgelagert #245**

_3. Beim Auto-Layout gibt es eine Funktion, bei der die Größe aller 'gleichwertiger Knoten' angepasst wird._

![image](https://user-images.githubusercontent.com/52324897/103890732-e33d1d00-50e8-11eb-94e6-404298d08d68.png)

**Comment by wehrlean** [comment]
1. und 2. widersprechen sich ein wenig. Soll der Knoten einfach immer länger werden oder soll er Zeilenumbrüchen machen und nach oben und unten verlängern? @fischJan 

Das obere oder das untere Verhalten?
![image](https://user-images.githubusercontent.com/49229000/104300589-faa04f80-54c6-11eb-9eeb-4d2021a560b7.png)

**Comment by fischJan** [comment]
Bitte des untere Verhalten. Und wenn man dann den Knoten wieder kleiner macht, muss es sich automatisch umbrechen, sodass der Text immer im Knoten bleibt. @wehrlean
