### ISSUE TITLE
Only link other models in linked nodes

### ISSUE THREAD

**Issue by sebeder** [qualicen/specmate#239]
**User Story**
As a user, I'd like do link nodes from only other models, so that I can create consistent models.

**Acceptance Criteria**
- In the dialog that appears, when a user creates a CEG Linked node, the currently open model is not listed.

**Comment by wehrlean** [comment]
@sebeder Ist eigentlich schon gemacht, oder? Wurde nur nicht geschlossen

**Comment by sebeder** [comment]
Ja, das ist schon gemacht.
