### ISSUE TITLE
Linked-Nodes Cycle Detector

### ISSUE THREAD

**Issue by sebeder** [qualicen/specmate#269]
**User Story**
As a user, I want to see whether I modelled cycles using linked nodes, so that I can model cycle-free (valid) CEG models.

**Acceptance Criteria**
- If there is a cycle (also with linked nodes over multiple models), the validator shows an error message.

**Comment by sebeder** [comment]
@junkerm @fischJan , this one is tricky to solve in the UI. Not the I could not implement it, but that one could impose rather expensive operations:

- We'd need to load every node that is reachable from another node (also via linked nodes, and thus, we can jump to different models)
- These nodes might not be in the current model, because they are linked
- These models might not even be loaded, and thus, it's contents are not loaded
- Therefore, we might load quite a lot of elements *from the server*
- And this is expensive

An alternative, which might be cheaper, is to **detect cycles in the backend** (e.g., during test spec generation or with a server side validator). What do you think? And this one is not that critical, since test spec generation handles the case gracefully.

**Comment by fischJan** [comment]
Hi :) @junkerm will be on vacation next week. I suggest that we skip this issue in the current sprint and move it to the next release. This allows us to clarify possible performance issues and to determine the "best solution approach". 

@sebeder Thanks for your quick "performance check"!
