### ISSUE TITLE
Cookie wird zu groß, wenn viele Jira Projekte existieren

### ISSUE THREAD

**Issue by fischJan** [qualicen/specmate#277]
**Describe the bug**
In der Testphase ist aufgefallen, dass wir (trotz vorhandener Lese- und Schreibrechte) nicht ordnungsgemäß auf die vom Multi Connector geladenen Jira Projekte zugreifen können. Der Connector ist in Prod somit aktuell nicht nutzbar.

**To Reproduce**
1. Click on a random Jira Project
2. Type in credentials
3. Login seems to work
4. However, after a few seconds you will be logged out again.

**Expected behavior**
Ich werde nicht ausgeloggt und kann mit der Modellierung anfangen.

**Additional context**
Das Problem besteht wohl in der Größe des Cookies (er wird größer als die maximale erlaubte Anzahl von 4096 Bytes). Wir müssen herausfinden, warum wir "so viel im Cookie" speichern und eine geeignete Lösung. Dieser Fehler ist definitiv geschäftskritisch und muss bis zum PROD deployment beseitigt werden.

@hauptmab: Sprech dich hier bitte mit @sebeder ab und klärt gemeinsam was man hier machen kann. Wir müssen das Verhalten dann wie gesagt noch auf DEV testen, das heißt die Deadline für die Bugreinigung ist der 05.03.21. Danke!

**Comment by sebeder** [comment]
Ich denke, dass wir diese Regex mit den allowed projects dann wohl nicht in einen Cookie schreiben dürfen, sondern über einen extra Service anbieten müssen. Das müsste der Client sich dann einfach holen. Frage: Wer implementiert das im Backend? Ich hab davon so ziemlich keine Ahnung, kann aber gerne die Geschichte im Frontend übernehmen.
