### ISSUE TITLE
In the CEG Editor the labels "AND" and "OR"  are not translated to german

### ISSUE THREAD

**Issue by junkerm** [qualicen/specmate#330]
**Describe the bug**
In the CEG Editor the labels "AND" and "OR"  are not translated to german

**Expected behavior**
The "AND" and "OR" labels are translated to "UND" and "ODER" if the langauge is set to german

**Comment by sebeder** [comment]
Hi @junkerm , @wehrlean ,
who will look into that? Do we need this until tomorrow?

**Comment by wehrlean** [comment]
It was an issue for tomorrow, but I have no time, sorry

**Comment by sebeder** [comment]
OK - I'll try my best.
